from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
from pptx.dml.color import RGBColor
import pandas as pd
import io

def create_ppt(df_latest):
    """
    Generates a PPTX file from the latest MCSA data.
    Returns a BytesIO object containing the PPTX file.
    """
    prs = Presentation()
    
    # --- Title Slide ---
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    title = slide.shapes.title
    subtitle = slide.placeholders[1]
    
    title.text = "Laporan MCSA & Kondisi Equipment"
    subtitle.text = "Generated by MCSA Assistant"
    
    # --- Summary Slide ---
    # Count conditions
    # We look for the 'Kondisi' parameter for each equipment
    df_cond = df_latest[df_latest['Parameter'] == 'Kondisi']
    
    # If 'Kondisi' parameter is not found for some reason, we skip summary stats logic or adapt
    if not df_cond.empty:
        status_counts = df_cond['Raw_Value'].value_counts()
        
        bullet_slide_layout = prs.slide_layouts[1]
        slide = prs.slides.add_slide(bullet_slide_layout)
        shapes = slide.shapes
        title_shape = shapes.title
        title_shape.text = "Ringkasan Kondisi Fleet"
        
        body_shape = shapes.placeholders[1]
        tf = body_shape.text_frame
        
        for status, count in status_counts.items():
            p = tf.add_paragraph()
            p.text = f"{status.title()}: {count} Equipment"
            p.level = 0
            
    # --- Detail Slides (Per Equipment) ---
    # Get list of unique equipment
    equipments = df_latest['Equipment'].unique()
    
    for eq in equipments:
        # Create a blank slide or title+content
        slide_layout = prs.slide_layouts[5] # Title Only
        slide = prs.slides.add_slide(slide_layout)
        shapes = slide.shapes
        
        title_shape = shapes.title
        title_shape.text = f"Detail: {eq}"
        
        # Get data for this equipment
        eq_data = df_latest[df_latest['Equipment'] == eq]
        
        # Determine overall condition for header color or indicator
        cond_row = eq_data[eq_data['Parameter'] == 'Kondisi']
        condition = cond_row['Raw_Value'].iloc[0] if not cond_row.empty else "Unknown"
        
        # Add a visual indicator (colored rectangle)
        left = Inches(8)
        top = Inches(0.5)
        width = Inches(1.5)
        height = Inches(0.5)
        shape = slide.shapes.add_shape(
            1, left, top, width, height # 1 is msoShapeRectangle
        )
        shape.text = condition.upper()
        
        fill = shape.fill
        fill.solid()
        cond_str = str(condition).lower()
        
        if 'normal' in cond_str:
            fill.fore_color.rgb = RGBColor(0, 255, 0) # Hijau
        elif 'high' in cond_str or 'bad' in cond_str or 'critical' in cond_str:
            fill.fore_color.rgb = RGBColor(255, 0, 0) # Merah
        elif 'alarm' in cond_str or 'warning' in cond_str:
            fill.fore_color.rgb = RGBColor(255, 255, 0) # Kuning
        else:
            fill.fore_color.rgb = RGBColor(192, 192, 192) # Grey
            
        # Add Table
        # Columns: Parameter, Value, Unit, Limit
        rows = len(eq_data) + 1
        cols = 4
        left = Inches(0.5)
        top = Inches(1.5)
        width = Inches(9.0)
        height = Inches(0.8)
        
        table = shapes.add_table(rows, cols, left, top, width, height).table
        
        # Header
        table.cell(0, 0).text = "Parameter"
        table.cell(0, 1).text = "Nilai Terakhir"
        table.cell(0, 2).text = "Satuan"
        table.cell(0, 3).text = "Limit"
        
        # Rows
        for i, (_, row) in enumerate(eq_data.iterrows()):
            table.cell(i+1, 0).text = str(row['Parameter'])
            val = row['Raw_Value']
            table.cell(i+1, 1).text = str(val) if pd.notna(val) else "-"
            table.cell(i+1, 2).text = str(row['Unit']) if pd.notna(row['Unit']) else ""
            table.cell(i+1, 3).text = str(row['Limit']) if pd.notna(row['Limit']) else ""
            
    # Save to buffer
    output = io.BytesIO()
    prs.save(output)
    output.seek(0)
    return output

if __name__ == "__main__":
    from data_loader import load_mcsa_data, get_latest_data, get_data_path
    df = load_mcsa_data(get_data_path('Report MCSA.xls'))
    latest = get_latest_data(df)
    ppt_io = create_ppt(latest)
    with open("test_output.pptx", "wb") as f:
        f.write(ppt_io.read())
    print("PPT Generated successfully.")
